import {Value} from './value';

export const NumberValues: Value[] = [
  {
    value: 0,
    type: 'number',
    strictType: 'number',
    passableFunctions: [
      'isNumber',
      'isFiniteNumber',
      'isInt',
    ],
  },
  {
    value: -1,
    type: 'number',
    strictType: 'number',
    passableFunctions: [
      'isNumber',
      'isFiniteNumber',
      'isNegativeNumber',
      'isNegativeFiniteNumber',
      'isInt',
    ],
  },
  {
    value: 1,
    type: 'number',
    strictType: 'number',
    passableFunctions: [
      'isNumber',
      'isFiniteNumber',
      'isPositiveNumber',
      'isPositiveFiniteNumber',
      'isInt',
    ],
  },
  {
    value: -1.24,
    type: 'number',
    strictType: 'number',
    passableFunctions: [
      'isNumber',
      'isFiniteNumber',
      'isNegativeNumber',
      'isNegativeFiniteNumber',
    ],
  },
  {
    value: 1.24,
    type: 'number',
    strictType: 'number',
    passableFunctions: [
      'isNumber',
      'isFiniteNumber',
      'isPositiveNumber',
      'isPositiveFiniteNumber',
    ],
  },
  {
    value: Infinity,
    type: 'number',
    strictType: 'number',
    passableFunctions: [
      'isNumber',
      'isInfinity',
      'isPositiveNumber',
    ],
  },
  {
    value: -Infinity,
    type: 'number',
    strictType: 'number',
    passableFunctions: [
      'isNumber',
      'isInfinity',
      'isNegativeNumber',
    ],
  },
  {
    value: new Number(),
    type: 'object',
    strictType: 'object',
    passableFunctions: [],
  },
  {
    value: '0',
    type: 'string',
    strictType: 'string',
    passableFunctions: [
      'isString',
      'isStringifiedNumber',
      ['isNumber', true],
      'isStringifiedFiniteNumber',
      ['isFiniteNumber', true],
      'isStringifiedInt',
      ['isInt', true],
    ],
  },
  {
    value: '-1',
    type: 'string',
    strictType: 'string',
    passableFunctions: [
      'isString',
      'isStringifiedNumber',
      ['isNumber', true],
      'isStringifiedFiniteNumber',
      ['isFiniteNumber', true],
      'isStringifiedNegativeNumber',
      ['isNegativeNumber', true],
      'isStringifiedNegativeFiniteNumber',
      ['isNegativeFiniteNumber', true],
      'isStringifiedInt',
      ['isInt', true],
    ],
  },
  {
    value: '1',
    type: 'string',
    strictType: 'string',
    passableFunctions: [
      'isString',
      'isStringifiedNumber',
      ['isNumber', true],
      'isStringifiedFiniteNumber',
      ['isFiniteNumber', true],
      'isStringifiedPositiveNumber',
      ['isPositiveNumber', true],
      'isStringifiedPositiveFiniteNumber',
      ['isPositiveFiniteNumber', true],
      'isStringifiedInt',
      ['isInt', true],
    ],
  },
  {
    value: '-1.24',
    type: 'string',
    strictType: 'string',
    passableFunctions: [
      'isString',
      'isStringifiedNumber',
      ['isNumber', true],
      'isStringifiedFiniteNumber',
      ['isFiniteNumber', true],
      'isStringifiedNegativeNumber',
      ['isNegativeNumber', true],
      'isStringifiedNegativeFiniteNumber',
      ['isNegativeFiniteNumber', true],
    ],
  },
  {
    value: '1.24',
    type: 'string',
    strictType: 'string',
    passableFunctions: [
      'isString',
      'isStringifiedNumber',
      ['isNumber', true],
      'isStringifiedFiniteNumber',
      ['isFiniteNumber', true],
      'isStringifiedPositiveNumber',
      ['isPositiveNumber', true],
      'isStringifiedPositiveFiniteNumber',
      ['isPositiveFiniteNumber', true],
    ],
  },
  {
    value: 'Infinity',
    type: 'string',
    strictType: 'string',
    passableFunctions: [
      'isString',
      'isStringifiedNumber',
      ['isNumber', true],
      'isStringifiedInfinity',
      ['isInfinity', true],
      'isStringifiedPositiveNumber',
      ['isPositiveNumber', true],
    ],
  },
  {
    value: '+Infinity',
    type: 'string',
    strictType: 'string',
    passableFunctions: [
      'isString',
      'isStringifiedNumber',
      ['isNumber', true],
      'isStringifiedInfinity',
      ['isInfinity', true],
      'isStringifiedPositiveNumber',
      ['isPositiveNumber', true],
    ],
  },
  {
    value: '-Infinity',
    type: 'string',
    strictType: 'string',
    passableFunctions: [
      'isString',
      'isStringifiedNumber',
      ['isNumber', true],
      'isStringifiedInfinity',
      ['isInfinity', true],
      'isStringifiedNegativeNumber',
      ['isNegativeNumber', true],
    ],
  },
]
